# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rssaurus < Formula
  desc "RSSaurus command-line client"
  homepage "https://rssaurus.com"
  version "0.1.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/RSSaurus/rssaurus-cli/releases/download/v0.1.5/rssaurus_0.1.5_darwin_amd64.tar.gz"
      sha256 "7f96a24c95cd1db55d7f98ec08e14dfad2c9ff30a96c95186f97d9908931ca0d"

      def install
        bin.install "rssaurus"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/RSSaurus/rssaurus-cli/releases/download/v0.1.5/rssaurus_0.1.5_darwin_arm64.tar.gz"
      sha256 "3706c8edeccb20756de54f0a22ca490d20643f6e8e6db05bbd0c105a3a9f883c"

      def install
        bin.install "rssaurus"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/RSSaurus/rssaurus-cli/releases/download/v0.1.5/rssaurus_0.1.5_linux_amd64.tar.gz"
      sha256 "0ce33fc0670ef8913b1b1003d6145635456e3abac1a60d7602a0acbe80669ee5"
      def install
        bin.install "rssaurus"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/RSSaurus/rssaurus-cli/releases/download/v0.1.5/rssaurus_0.1.5_linux_arm64.tar.gz"
      sha256 "fec16b2f09b3f72189a1efa3bf059f3560771f690fc29cfe6c10e68029fc44ee"
      def install
        bin.install "rssaurus"
      end
    end
  end
end
