# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rssaurus < Formula
  desc "RSSaurus command-line client"
  homepage "https://rssaurus.com"
  version "0.1.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/RSSaurus/rssaurus-cli/releases/download/v0.1.4/rssaurus_0.1.4_darwin_amd64.tar.gz"
      sha256 "3123df1d311dce813bc9a924aff1f0edad9408a4707411f84f8fc1b701a551e4"

      def install
        bin.install "rssaurus"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/RSSaurus/rssaurus-cli/releases/download/v0.1.4/rssaurus_0.1.4_darwin_arm64.tar.gz"
      sha256 "c5c2fd0289b47a395174e19c1ab843cbf6fdea6da0c8e42365f41e2bc9a2d294"

      def install
        bin.install "rssaurus"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/RSSaurus/rssaurus-cli/releases/download/v0.1.4/rssaurus_0.1.4_linux_amd64.tar.gz"
      sha256 "8b3c79cf9dfa9adb4aa6c81e563790611c98f25c1ed26e3a61f2c9d391bdcbee"
      def install
        bin.install "rssaurus"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/RSSaurus/rssaurus-cli/releases/download/v0.1.4/rssaurus_0.1.4_linux_arm64.tar.gz"
      sha256 "7351302ee85fb6c662cfda3aab8e1587aba5823f40f60335f8e1711a70d898b7"
      def install
        bin.install "rssaurus"
      end
    end
  end
end
